### ISSUE TITLE
The gradle-ci example is empty

### ISSUE THREAD

**Issue by nucatus** [JFrogDev/project-examples#48]
The CI example is not providing the right build.gradle script. Am I missing something?

https://github.com/JFrogDev/project-examples/blob/master/gradle-examples/4/gradle-example-ci-server/build.gradle

**Comment by eyalbe4** [comment]
@nucleus,
Can you please clarify what you mean by "not providing the right build.gradle script"? Are you referring to the fact that the artifactory closure is not defined in the script? If so, it is not defined because the closure is added by the CI Server (Jenkins, Bamboo or TeamCity) as described in the gradle-examoles README.rd. If you feel the README should be improved or extended, feel free to suggest the changes or submit a pull request.

**Comment by nucatus** [comment]
Hi @eyalbe4 
That makes more sense now. Thanks for the clarifications. I was completely skipping the readme for some unknown reasons :)
