### ISSUE TITLE
[Question][Usage] Sample on using pointers to Artifactory 

### ISSUE THREAD

**Issue by sks** [JFrogDev/project-examples#81]
Hi Team,

Could someone please provide a sample on how to have symlinks in artifactory?

Use case:

As soon as an artifact is uploaded to artifactory, I wish to have a symlink pointed to that artifactory ?

something similar to ` current ` / ` develop `.

Please let me know in case more info is required from my side.

**Comment by eyalbe4** [comment]
@sks,
Can you please elaborate more about the use case? I'm not sure I got it.
JFrog CLI includes the functionality of storing symlinks in Artifactory, by uploading existing symlinks from the local file-system, so that they can be later downloaded and recreated on the file-system.
You can read more about it in the JFrog CLI User Guide.
Is this what you're looking for?

**Comment by sks** [comment]
Yes,

That is the exact functionality I wanted,

Is that supported in artifactory plugin ?

**Comment by eyalbe4** [comment]
No @sks,
It is currently supported in JFrog CLI only.
You can probably use JFrof CLI from any of the CI plugins.

**Comment by sks** [comment]
Thanks @eyalbe4. Will check on that option then

**Comment by sks** [comment]
Thanks @eyalbe4. Will check on that option then
